// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX8MpWWX9fElMjzLzS9XCA7E12uSvzXjs',
    appId: '1:49724108296:web:d8433afa144ddcf8cfebbd',
    messagingSenderId: '49724108296',
    projectId: 'mynotes-da5cc',
    authDomain: 'mynotes-da5cc.firebaseapp.com',
    storageBucket: 'mynotes-da5cc.firebasestorage.app',
    measurementId: 'G-0RZCW07JZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnc8dwiYCMHh7e5L47wGCfY5qaMG5Xv1Q',
    appId: '1:49724108296:android:1b9f5dea2a87ae8bcfebbd',
    messagingSenderId: '49724108296',
    projectId: 'mynotes-da5cc',
    storageBucket: 'mynotes-da5cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS_PaLZ0KEtJLd_m4j97aMEK8_0Ov16pc',
    appId: '1:49724108296:ios:ce099f3af6cf90d2cfebbd',
    messagingSenderId: '49724108296',
    projectId: 'mynotes-da5cc',
    storageBucket: 'mynotes-da5cc.firebasestorage.app',
    iosBundleId: 'com.hinglajma.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS_PaLZ0KEtJLd_m4j97aMEK8_0Ov16pc',
    appId: '1:49724108296:ios:ce099f3af6cf90d2cfebbd',
    messagingSenderId: '49724108296',
    projectId: 'mynotes-da5cc',
    storageBucket: 'mynotes-da5cc.firebasestorage.app',
    iosBundleId: 'com.hinglajma.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX8MpWWX9fElMjzLzS9XCA7E12uSvzXjs',
    appId: '1:49724108296:web:5d6ec014902ac895cfebbd',
    messagingSenderId: '49724108296',
    projectId: 'mynotes-da5cc',
    authDomain: 'mynotes-da5cc.firebaseapp.com',
    storageBucket: 'mynotes-da5cc.firebasestorage.app',
    measurementId: 'G-9ZJBD23M5H',
  );

}